### ISSUE TITLE
[FR] Converters for the Sha256 type

### ISSUE THREAD

**Issue by stevenroose** [rust-bitcoin/rust-lightning-invoice#23]
Converters for `Sha256dHash` or `sha256::Hash` would be great. So that I can use the Display and FromStr implementation from those classes.

**Comment by sgeisler** [comment]
The inner `sha256::Hash` is already public. I agree that writing `hash.0` isn't super ergonomic, but I don't think `From`/`Into` would help much.

But I think that the invoice struct should return `sha256::Hash` from [`payment_hash(&self)`](https://github.com/rust-bitcoin/rust-lightning-invoice/blob/master/src/lib.rs#L969). The `Invoice` API should be as ergonomic as possible, if you want to dive deeper by using `RawInvoice` etc. be prepared for some newtype bloat (I had to wrap everything in newtypes to implement my custom serialization).

**Comment by stevenroose** [comment]
Yeah the code of this crate very much confuses me. The whole idea of keeping the fields around and so might have overcomplicated it.

Don't you think it'd be able to take an approach like @dongcarl's PSBT implementation where you just assign all fields during deserialization?

**Comment by sgeisler** [comment]
What exactly confuses you? I'd be happy to document the design better :) I basically build an AST (`SignedRawInvoice`/`RawInvoice`) and then you can optionally validate it and turn it into an actual `Invoice` that can have a more natural API since the validation gave it guarantees about which fields are actually present.

I really like the design of separating parsing from validation. It also allows you to create invalid, but parseble invoices (`RawSignedInvoice`) to mess around with other implementations. I'm all for keeping the high level API (`Invoice`) as simple as possible, but the layering is intentional, I even wanted to go further but prioritized finishing the crate.

For example I'd love to add optional meta information about which characters in the bech32 invoices correspond with which parsed fields so you could build a visualization of that. But I haven't found a good abstraction, that has no overhead if you don't want to use it, yet.

**Comment by stevenroose** [comment]
The separation between the 3 or 4 invoice types and how the getters are delegated to the fields etc.

Well, the code is here and it works, but I think a simple struct like this could have been sufficient:
```rust
pub struct Invoice {
	pub timestamp: SystemTime,
	pub payment_hash: Sha256dHash,
	pub description: Option<String>,
	pub description_hash: Sha256dHash,
	pub payee_pub_key: Option<secp256k1::PublicKey>,
	pub expiry_time: Option<SystemTime>,
	pub min_final_cltv_expiry: Option<u32>,
	pub fallback_addresses: Vec<bitcoin::Addresss>,
	pub routes: Vec<Route>,
	pub currency: Currency,
	pub amount_pico_btc: Option<u64>,
	pub unknown_fields: Vec<InvoiceField>,
}
```
See PSBT f.e.: https://github.com/rust-bitcoin/rust-bitcoin/pull/103/files#diff-02296c2111f0e9a7c51694b2d6ac6877R31

**Comment by sgeisler** [comment]
This struct doesn't enforce all the rules of valid invoices, so I had to check that on serialization. And the ser/de functions would be a big mess, doing everything in one function. I'm actually pretty proud of the builder that enforces most restrictions using the type system (using the `tb` module).

I  think the approach I took leads to more code, but has a cleaner and more flexible architecture.

Btw: does `hash.0` solve your problem? Then I'd close this issue and concentrate on #26

**Comment by stevenroose** [comment]
> Btw: does `hash.0` solve your problem? Then I'd close this issue and concentrate on #26

I think it does.

Hmm, yeah I think the "semantical restrictions" are bigger in these invoices than they are in the PSBT spec, so a builder with extra constraint checking makes sense.
