### ISSUE TITLE
Upload to crates

### ISSUE THREAD

**Issue by TheBlueMatt** [rust-bitcoin/rust-lightning-invoice#5]
Seems this isnt on crates.io yet, can you upload it?

**Comment by sgeisler** [comment]
It's far from finished. I'm doing a rather largish refactoring right now. This will introduce newtypes for all tagged fields etc. and break the API. I'm still figuring out the best way to get to a coherent and simple architecture, but I think by using `FromBase32` and `ToBase32` and newtypes. In the end I will also split the structures in `RawX` for syntactically correct invoices and `X` for the syntactically checkec counterpart. For example a `RawInvoice` may have an arbitrary `n` field (public key) and by calling `check(self)` on it you get an error or an `Invoice` where the public key must be the one used for the signature.

Is there an urgent need for it to be uploaded? Otherwise I'd like to figure these things out first.

**Comment by TheBlueMatt** [comment]
Not a huge rush, I've been testing rust-lightning against real nodes on testnet using https://github.com/TheBlueMatt/rust-lightning-bitcoinrpc and was trying to use this to parse invoices and found the awkwardness I already filed. Obviously the whole rust-lightning thing is still a fast-moving target so I'm using git for now anyway.
